### ISSUE TITLE
skyline lab failed on tests

### ISSUE THREAD

**Issue by Z-Y00** [FluorineDog/sml_homework_dog#2]
I added a few tests, and your code failed to pass some of them

![image](https://user-images.githubusercontent.com/23717414/33754516-70eb348e-dbe4-11e7-92c9-16c78b465e08.png)

**Comment by FluorineDog** [comment]
I don't regard inputs with duplicate x as valid, so this behavior is a feature. 
if you insist, add a filter layer which checks whether values are increasing at same point to filter out the unnecessary ones. 
AGAIN, no fix is expected.
